### ISSUE TITLE
[docs] TODO list for the first release

### ISSUE THREAD

**Issue by irmana** [bleenco/abstruse#46]
- [x] Wiki: Installation instructions
- [ ] Wiki: how to change SQLite/Postgres/Mysql
- [ ] Wiki: how to backup abstruse
- [ ] Benchmark: Abstruse, Jenkins, Drone, Travis, Strider, Go, Integrity
- [x] Update README
- [ ] Do the final check of all docs
